# Generated by Django 2.1.3 on 2018-11-23 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_votacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='votacao',
            name='votoscandidato1',
        ),
        migrations.RemoveField(
            model_name='votacao',
            name='votoscandidato2',
        ),
        migrations.AlterField(
            model_name='candidatos',
            name='imagem',
            field=models.ImageField(upload_to='fotoscandidatos'),
        ),
        migrations.AddField(
            model_name='voto',
            name='votacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_votacao.Votacao'),
        ),
    ]
