# Generated by Django 2.1.3 on 2018-11-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_votacao', '0002_auto_20181123_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='votacao',
            name='nome',
            field=models.CharField(default='', max_length=255),
        ),
    ]
