# Generated by Django 2.1.3 on 2018-11-25 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_votacao', '0003_votacao_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatos',
            options={'verbose_name': '2 - Candidatos', 'verbose_name_plural': '2 - Candidatos'},
        ),
        migrations.AlterModelOptions(
            name='usuarioperfil',
            options={'verbose_name': '1 - Perfis dos Usuários', 'verbose_name_plural': '1 - Perfis dos Usuários'},
        ),
        migrations.AlterModelOptions(
            name='votacao',
            options={'verbose_name': '3 - Votações', 'verbose_name_plural': '3 - Votações'},
        ),
        migrations.AlterModelOptions(
            name='voto',
            options={'verbose_name': '4 - Votos', 'verbose_name_plural': '4 - Votos'},
        ),
        migrations.AlterField(
            model_name='voto',
            name='voto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_votacao.Candidatos'),
        ),
    ]
